[package]
name = "openai-tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dotenvy = "0.15.7"
fxhash = "0.2.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"

[package.metadata.release]
tag = true
